---
- name: Install Citrix License Server Pre-Reqs
  win_feature:
    name:
      - NET-Framework-Core
      - NET-Framework-Features
      - NET-Framework-45-Features
      - NET-Framework-45-Core
      - NET-Framework-45-ASPNET
    state: present
  register: win_feature

- name: Reboot to complete feature installation
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- name: Create Download Folder
  win_file:
    path: C:\Download
    state: directory

- name: Create Citrix Download Folder
  win_file:
    path: C:\Download\Citrix
    state: directory

- name: Check if Citrix ISO is downloaded yet
  win_stat:
    path: C:\Download\Citrix\Citrix_Virtual_Apps_and_Desktops_7_2203.iso
  register: download_file

- name: Copy a single file
  ansible.windows.win_copy:
    src: files/Get-CTXBinary.ps1
    dest: C:\Download\Citrix\Get-CTXBinary.ps1

- name: Download Citrix Virtual Apps and Desktops 2203
  win_shell: C:\Download\Citrix\Get-CTXBinary.ps1 -DownloadNumber 20428 -DownloadFileName "Citrix_Virtual_Apps_and_Desktops_7_2203.iso" -DownloadPath C:\Download\Citrix\ -MyCitrixUsername "{{ citrix_username }}" -MyCitrixPassword "{{ citrix_password }}"
  register: citrix_download
  when: download_file.stat.exists == False

- name: Register iso path
  set_fact:
    iso_path: C:\Download\Citrix\Citrix_Virtual_Apps_and_Desktops_7_2203.iso
  when: download_file.stat.exists == True

- name: Register iso path
  set_fact:
    iso_path: "{{citrix_download.stdout | trim }}"
  when: download_file.stat.exists == False

- name: Debug Citrix download
  ansible.builtin.debug:
    msg: "{{ iso_path }}"

- name: Ensure an ISO is mounted
  win_disk_image:
    image_path: "{{ iso_path }}"
    state: present
  register: disk_image_out

- name: Install License Server
  win_package:
    path: "{{ disk_image_out.mount_paths[0] }}\\x64\\Licensing\\CTX_Licensing.msi"
    product_id: '{17086151-418C-40D7-B25B-1E5AE2F76DD0}'
    state: present
  register: lic_install

- name: Install License PowerShell Snapins
  win_package:
    path: "{{ disk_image_out.mount_paths[0] }}\\x64\\Licensing\\LicensingAdmin_PowerShellSnapin_x64.msi"
    product_id: '{A2D37E62-E9C1-4D75-8660-E2ACC5CBE99E}'
    state: present

- name: Open 2700 for lic
  community.windows.win_firewall_rule:
    name: Citrix License Server
    localport: 2700
    action: allow
    direction: in
    protocol: tcp
    profiles: [domain, private]
    state: present
    enabled: yes

- name: Reboot to complete installation
  ansible.windows.win_reboot:
  when: lic_install.changed