---
- name: Built the environment dictonary and variables
  set_fact:
    citrix_username: "{{ lookup('env', 'citrix_username') }}"
    citrix_password: "{{ lookup('env', 'citrix_password') }}"

- name: Install DDC Pre-Reqs
  win_feature:
    name:
    - NET-Framework-Core
    - NET-Framework-45-Core
    - NET-Framework-45-ASPNET
    - GPMC
    - RSAT-ADDS-Tools
    - RDS-Licensing-UI
    - WAS
    - Telnet-Client
    - GPMC
    - Remote-Assistance
    - RSAT-AD-Tools
    - Web-Server
    - Web-WebServer
    - Web-Common-Http
    - Web-Default-Doc
    - Web-Dir-Browsing
    - Web-Http-Errors
    - Web-Static-Content
    - Web-Http-Redirect
    - Web-Health
    - Web-Http-Logging
    - Web-Log-Libraries
    - Web-Http-Tracing
    - Web-Performance
    - Web-Stat-Compression
    - Web-Dyn-Compression
    - Web-Security
    - Web-Filtering
    - Web-Basic-Auth
    - Web-Windows-Auth
    - Web-Net-Ext45
    - Web-ASP
    - Web-ASP-Net45
    - Web-CGI
    - Web-ISAPI-Ext
    - Web-ISAPI-Filter
    - Web-Includes
    - Web-WebSockets
    - Web-Mgmt-Tools
    - Web-Mgmt-Console
    - Web-Mgmt-Compat
    - Web-Metabase
    - Web-Lgcy-Mgmt-Console
    - Web-Lgcy-Scripting
    - Web-WMI
    - Web-Scripting-Tools
    state: present
  register: win_feature

- name: Reboot to complete domain join
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- name: Create Log Folder
  win_file:
    path: C:\Logs
    state: directory

- name: Create Download Folder
  win_file:
    path: C:\Download
    state: directory

- name: Create Citrix Download Folder
  win_file:
    path: C:\Download\Citrix
    state: directory

- name: Check if Citrix ISO is downloaded yet
  win_stat:
    path: C:\Download\Citrix\Citrix_Virtual_Apps_and_Desktops_7_2203.iso
  register: download_file

- name: Copy a single file
  ansible.windows.win_copy:
    src: files/Get-CTXBinary.ps1
    dest: C:\Download\Citrix\Get-CTXBinary.ps1

- name: Download Citrix Virtual Apps and Desktops 2203
  win_shell: C:\Download\Citrix\Get-CTXBinary.ps1 -DownloadNumber 20428 -DownloadFileName "Citrix_Virtual_Apps_and_Desktops_7_2203.iso" -DownloadPath C:\Download\Citrix\ -MyCitrixUsername "{{ citrix_username }}" -MyCitrixPassword "{{ citrix_password }}"
  register: citrix_download
  when: download_file.stat.exists == False

- name: Register iso path
  set_fact:
    iso_path: C:\Download\Citrix\Citrix_Virtual_Apps_and_Desktops_7_2203.iso
  when: download_file.stat.exists == True

- name: Register iso path
  set_fact:
    iso_path: "{{citrix_download.stdout | trim }}"
  when: download_file.stat.exists == False

- name: Debug Citrix download
  ansible.builtin.debug:
    msg: "{{ iso_path }}"

- name: Ensure an ISO is mounted
  win_disk_image:
    image_path: "{{ iso_path }}"
    state: present
  register: disk_image_out

- name: Install DDC Components
  win_package:
    path: "{{ disk_image_out.mount_paths[0] }}\\x64\\XenDesktop Setup\\XenDesktopServerSetup.exe"
    arguments: /components controller,desktopstudio,desktopdirector /configure_firewall /nosql /noreboot /quiet /logpath C:\Logs
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: C:\Program Files\Citrix\Desktop Studio
    product_id: '{07EBAA9B-5D49-4C86-9571-834F4BE05FA8}'
  vars:
    ansible_become: yes
    ansible_become_user: GO\Administrator
    ansible_become_password: "{{ ansible_password }}"
    ansible_become_method: runas

- name: Reboot to complete DDC Install
  ansible.windows.win_reboot:

- name: Remove DDC RunOnce Key
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: "!XenDesktopSetup"
    state: absent
  register: ddc_resume

- name: Resume DDC Install
  win_package:
    path: C:\ProgramData\Citrix\XenDesktopSetup\XenDesktopServerSetup.exe
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: C:\Program Files\Citrix\Desktop Studio
  when: ddc_resume.changed