- name: Built the environment dictonary and variables
  set_fact:
    branch: "{{ lookup('env', 'branch') | lower }}"
    prefix: "{{ lookup('env', 'prefix') }}"
    citrix_org_id: "{{ lookup('env', 'citrix_org_id') }}"
    citrix_client_id: "{{ lookup('env', 'citrix_client_id') }}"
    citrix_client_secret: "{{ lookup('env', 'citrix_client_secret') }}"
    azure_region: "{{ lookup('env', 'azure_region') }}"
    branches:
        default: "pois" 
        cards:   "card"
        flowers: "flow"
    regions:
        westeurope: "West Europe"
        eastus: "East US"

- name: Set the environment short
  set_fact:
    environment_short: "{{ branches[branch | lower] }}"
    region: "{{ regions[azure_region | lower ] }}"

- name: Collect API access token from Citrix Cloud
  uri:
    url: "https://api.cloud.com/cctrustoauth2/{{ citrix_org_id }}/tokens/clients"
    method: POST
    body_format: form-urlencoded
    body: "grant_type=client_credentials&client_id={{ citrix_client_id }}&client_secret={{ citrix_client_secret }}"
    return_content: yes
  register: citrix_token

- name: Get Citrix Cloud sites
  uri:
    url: https://api.cloud.com/cvad/manage/Sites/{{ citrix_org_id }}
    method: GET
    body_format: json
    headers: 
      Citrix-CustomerId: "{{ citrix_org_id }}"
      Authorization: "CWSAuth bearer={{citrix_token.json.access_token}}"
    return_content: yes
  register: citrix_sites

- name: Set Citrix Cloud site ID
  set_fact:
    citrix_site_id: "{{ citrix_sites.json.Id }}"

- name: Get Citrix Cloud hypervisor connection
  uri:
    url: https://api.cloud.com/cvad/manage/hypervisors
    method: GET
    body_format: json
    headers:
      Citrix-CustomerId: "{{ citrix_org_id }}"
      Citrix-InstanceId: "{{ citrix_site_id }}"
      User-Agent: GET
      Authorization: "CWSAuth bearer={{citrix_token.json.access_token}}"
    return_content: yes
  register: citrix_hypervisor

- name: Set Citrix Cloud hypervisor ID
  set_fact:
    citrix_hypervisor_id: "{{ data | json_query(querystr) }}"
  vars:
    data: "{{ citrix_hypervisor.json }}"
    querystr: "Items[?contains(Name,'{{ prefix | lower }}-{{ environment_short }}-{{ deploymentname | lower }}-azure')].Id | [0]" #First result

- name: Get Citrix Cloud zones
  uri:
    url: "https://api.cloud.com/cvad/manage/zones"
    method: GET
    body_format: json
    headers: 
      Citrix-CustomerId: "{{ citrix_org_id }}"
      Citrix-InstanceId: "{{ citrix_site_id }}"
      User-Agent: GET
      Authorization: "CWSAuth bearer={{citrix_token.json.access_token}}"
    return_content: yes
  register: citrix_zones
  when: citrix_hypervisor_id == ""

- name: Set Citrix Cloud zone ID
  set_fact:
    citrix_zone_id: "{{ data | json_query(querystr) }}"
  vars:
    data: "{{ citrix_zones.json }}"
    querystr: Items[?Name == '{{ prefix | lower }}-{{ environment_short | lower }}-{{ deploymentname | lower }}'].Id | [0]
  when: citrix_hypervisor_id == ""

- name: Creating Citrix Cloud hosting body 
  set_fact: 
    hosting_object:
      ConnectionDetails:
        Name: "{{ prefix | lower }}-{{ environment_short | lower }}-{{ deploymentname }}-azure"
        ConnectionType: AzureRM
        ApplicationId: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        ApplicationSecret: "{{ lookup('env', 'AZURE_SECRET') }}"
        SubscriptionId: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        ActiveDirectoryId: "{{ lookup('env', 'AZURE_TENANT') }}"
        Environment: AzureCloud
        Zone: "{{ citrix_zone_id }}"
  when: citrix_hypervisor_id == ""

- name: Post Citrix Cloud hypervisor connection
  uri:
    url: https://api.cloud.com/cvad/manage/hypervisors
    method: POST
    body_format: json
    headers: 
      Citrix-CustomerId: "{{ citrix_org_id }}"
      Citrix-InstanceId: "{{ citrix_site_id }}" 
      User-Agent: POST
      Authorization: "CWSAuth bearer={{citrix_token.json.access_token}}"
    body: "{{ hosting_object | to_json }}"
    status_code: [200, 201]
    return_content: yes
  register: citrix_new_hypervisor
  when: citrix_hypervisor_id == ""

- name: Set the new hypervisor id
  set_fact:
    citrix_hypervisor_id: "{{ citrix_new_hypervisor.json.Id }}"
    msg: "{{ citrix_new_hypervisor }}"
  when: citrix_hypervisor_id == ""

- name: Get Citrix Cloud hypervisor resources
  uri:
    url: "https://api.cloud.com/cvad/manage/hypervisors/{{ citrix_hypervisor_id }}/resourcePools"
    method: GET
    body_format: json
    headers: 
      Citrix-CustomerId: "{{ citrix_org_id }}"
      Citrix-InstanceId: "{{ citrix_site_id }}" 
      User-Agent: GET
      Authorization: "CWSAuth bearer={{citrix_token.json.access_token}}" 
    return_content: yes
  register: citrix_hypervisor_resource

- name: Set Citrix Cloud hypervisor resource ID
  set_fact:
    citrix_hypervisor_resource_id: "{{ data | json_query(querystr) }}"
  vars:
    data: "{{ citrix_hypervisor_resource.json }}"
    querystr: "items[?contains(name,'{{ prefix | lower }}-{{ environment_short }}-{{ deploymentname | lower }}-azure')].id | [0]"

- name: Creating Citrix Cloud resource body 
  set_fact: 
    resource_object:
      Name: "{{ prefix | lower }}-{{ environment_short }}-{{ deploymentname }}-default"
      ConnectionType: AzureRM
      Region: "{{ region }}.region"
      VirtualNetwork: "{{ region }}.region/virtualprivatecloud.folder/rg-golab-{{ environment_short }}-vnet.resourcegroup/vnet-infra-{{ environment_short }}.virtualprivatecloud"
      Subnets: [ "{{ region }}.region/virtualprivatecloud.folder/rg-golab-{{ environment_short }}-vnet.resourcegroup/vnet-infra-{{ environment_short }}.virtualprivatecloud/sn-infra-{{ environment_short }}.network" ]
  when: citrix_hypervisor_resource_id == ""

- name: Post Citrix Cloud resource pool
  uri:
    url: https://api.cloud.com/cvad/manage/hypervisors/{{ citrix_hypervisor_id }}/resourcePools
    method: POST
    headers: 
      Citrix-CustomerId: "{{ citrix_org_id }}"
      Citrix-InstanceId: "{{ citrix_site_id }}" 
      User-Agent: POST
      Authorization: "CWSAuth bearer={{citrix_token.json.access_token}}" 
    body_format: json
    body: "{{ resource_object | to_json }}"
    return_content: yes
    status_code: [200, 201]
  register: citrix_new_resource
  when: citrix_hypervisor_resource_id == ""
