---
- name: Install Microsoft Visual C++ Redistributable Latest - X86"
  win_package:
    path: https://aka.ms/vs/17/release/vc_redist.x86.exe
    arguments: /q /norestart

- name: Install Microsoft Visual C++ Redistributable Latest - X64"
  win_package:
    path: https://aka.ms/vs/17/release/vc_redist.x64.exe
    arguments: /q /norestart

- name: Install Microsoft .NET Framework 4.8 - Offline installer
  win_package:
    path: https://go.microsoft.com/fwlink/?linkid=2088631
    arguments: /q /norestart

- name: Reboot to complete Windows Feature installation
  win_reboot:
    reboot_timeout: 3600

- name: Install Citrix VDA
  win_package:
    path: "{{citrix.path}}/{{citrix.version}}/VDAWorkstationSetup_{{citrix.version}}.exe"
    arguments: /components VDA /disableexperiencemetrics /enable_hdx_ports /enable_hdx_udp_ports /enable_real_time_transport /masterimage /noreboot /quiet
    state: present
    expected_return_code: [0, 3, 3010]
  register: vda_install

- name: Reboot after VDA
  win_reboot:
  when: vda_install.changed
