- name: Domain join machine
  block:
  
  - name: Check for PowerShellGet & PackageManagement modules
    win_psmodule:
      name: PowerShellGet
      state: present
    retries: 5
    delay: 30
    loop:
      - PowerShellGet
      - PackageManagement

  - name: Install package provider NuGet
    win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

  - name: Check for xDSCDomainjoin DSC Powershell module
    win_psmodule:
      accept_license: true
      name: xDSCDomainjoin
      state: present
    retries: 5
    delay: 30
    register: result
    until: result is not failed

  - name: Domain join
    win_dsc:
      resource_name: xDSCDomainjoin
      Domain: '{{ dns_domain_name }}'
      Credential_username: '{{ domain_admin_user }}'
      Credential_password: '{{ ansible_password }}'
    register: domain_state
    retries: 2
    delay: 30
    until: domain_state is not failed

  - name: Reboot to complete domain join
    win_reboot:
    when: domain_state.reboot_required

  when: ansible_facts['windows_domain_member'] == false