---
- name: Domain join machine
  block:

  - name: Set timezone to 'W. Europe Standard Time' (GMT+01:00)
    win_timezone:
      timezone: W. Europe Standard Time

  - name: Set fact for Domain Path
    set_fact:
      domain_path: "DC={{ dns_domain_name.split('.') | join(',DC=') }}"

  # - name: Set DNS to primary domain controller
  #   win_dns_client:
  #     adapter_names: '*'
  #     ipv4_addresses:
  #       - "{{ hostvars[groups['dc'][0]].ansible_host }}"

  - name: Domain join
    win_domain_membership:
      dns_domain_name: "{{ dns_domain_name }}"
      hostname: "{{ inventory_hostname }}"
      domain_admin_user: "{{ domain_admin_user }}"
      domain_admin_password: "{{ domain_password }}"
      domain_ou_path: "{{ ou_path }},{{ domain_path }}"
      state: domain
    register: domain_state
    retries: 2
    delay: 30
    until: domain_state is not failed

  - name: Reboot to complete domain join
    win_reboot:
    when: domain_state.reboot_required

  when: ansible_facts['windows_domain_member'] == false
