- name: Collect hostname
  win_shell: |
      $env:COMPUTERNAME
  register: hostname

- name: Set strong cryptography
  win_shell: |
      Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
      Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
  vars:
    ansible_become: yes
    ansible_become_user: system
    ansible_become_method: runas

- name: Install NuGet
  win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

- name: Check for xDSCDomainjoin DSC Powershell module
  win_psmodule:
    name: xDSCDomainjoin
    state: present

- name: Domain join
  win_dsc:
    resource_name: xDSCDomainjoin
    Domain: '{{ dns_domain_name }}'
    Credential_username: '{{ domain_admin_user }}'
    Credential_password: '{{ ansible_password }}'
  register: domain_state
  retries: 2
  delay: 30

- name: Reboot to complete domain join
  win_reboot:
  when: domain_state.reboot_required