---
- name: Update fact to AdobeAcrobatReaderDC
  set_fact:
    app_name: AdobeAcrobatReaderDC

- name: "Collect Evergreen info for {{ app_name }}"
  win_uri:
    url: "https://evergreen-api.stealthpuppy.com/app/{{ app_name }}"
    method: GET
    content_type: application/json
    return_content: true
  register: app

- name: "Set Evergreen object for {{ app_name }}"
  set_fact:
    app_details: "{{ app.json | json_query('[?Architecture == `x64` && Language == `MUI`]') | first }}"

- name: "Install {{ app_details.Title }} {{ app_details.Version }}"
  win_package:
    path: "{{ app_details.URI }}"
    arguments: /sAll /rs /msi EULA_ACCEPT=YES
    expected_return_code: [0, 3, 3010]
    state: present
