---
- name: Deployment Information
  debug:
    msg: "Running deployment for {{delivery}} on {{ansible_facts.os_name}}"

- name: Add registry DelayedDesktopSwitchTimeout to value 0
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: DelayedDesktopSwitchTimeout
    data: 0
    type: dword

- name: Install NVIDIA driver
  import_tasks: nvidia.yml

- name: Install LoadGen
  import_tasks: loadgen-addin.yml

- name: Install Citrix VDA
  import_tasks: citrix-vda.yml

- name: Install VMware Horizon
  import_tasks: vmware-horizon.yml
  when: delivery == 'vmware'

- name: Install Office 365
  import_tasks: office365.yml

- name: Install Adobe Reader DC
  import_tasks: adobe-reader-dc.yml

- name: Apply Windows updates
  import_tasks: updates.yml

- name: Hardening Kitty Install
  hardening_kitty:
    state: present

# - name: Hardening Kitty Apply
#   hardening_kitty:
#     state: present

- name: Apply Citrix Optimizer
  import_tasks: citrix-optimizer.yml

# - name: Microsoft Defender
#   import_tasks: microsoft-defender.yml

- name: Deployment Information
  debug:
    msg: "Complete deployment"

# - name: Shutdown deployment machine
#   win_shell: shutdown -s -f -t 30