---
- name: Install VMware Horizon Agent
  win_package:
    path: "{{vmware.path}}/{{vmware.version}}/{{vmware.agent.source}}"
    arguments: /s /v"/qn REBOOT=Reallysuppress VDM_VC_MANAGED_AGENT=1 ADDLOCAL=Core,USB,RTAV,NGVC,VmwVaudio"
    state: present
    creates_path: C:\Program Files\VMware\VMware View\Agent
    expected_return_code: [0, 3010]
  vars:
    ansible_become: true
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"
    ansible_become_method: runas
  register: install

- name: Reboot
  win_reboot:
  when: install.reboot_required
