---
- name: Create Parallels RAS Farm
  ras_farm:
    gateway: "{{ ansible_hostname }}.{{ dns_domain_name }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    provider_type: "VCenter"
    provider_server: "{{ vmware.vsphere.name }}.{{ dns_domain_name }}"
    provider_username: "{{ vsphere_username }}"
    provider_password: "{{ vsphere_password }}"
    provider_version: "v8_0"
    state: present
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"