- name: Set fac
  set_fact:
    domain_path: "dc=GO,dc=EUC"

- name: Check for ActiveDirectory DSC Powershell module
  win_psmodule:
    name: ActiveDirectoryDsc
    state: present
  retries: 5 

- name: Create OU
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: GO
    path: "{{ domain_path }}"

- name: Create OU
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "{{ item }}"
    path: "OU=GO,{{ domain_path }}"
  loop:
    - Accounts
    - Groups
    - LoadGen
    - ServiceAccounts
    - Machines

- name: Create OU
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "{{ item }}"
    path: "OU=Machines,OU=GO,{{ domain_path }}"
  loop:
    - Bots
    - Builds
    - GPU
    - Infra
    - RDS
    - VDI

- name: Ensure the group Loadgen exists using sAMAccountName
  win_domain_group:
    name: LoadGen
    scope: global
    path: "OU=Groups,OU=GO,{{ domain_path }}"

- name: Create RDGateway Group
  win_domain_group:
    name: 'RD Gateway Users'
    scope: global
    path: "OU=Groups,OU=GO,{{ domain_path }}"

- name: Create Service accounts
  win_domain_user:
    name: sql_svc
    password: '{{ ansible_password }}'
    state: present
    path: "OU=ServiceAccounts,OU=GO,{{ domain_path }}"
    description: SQL Server - Service Account

- name: Create Service accounts
  win_domain_user:
    name: sql_agt
    password: '{{ ansible_password }}'
    state: present
    path: "OU=ServiceAccounts,OU=GO,{{ domain_path }}"
    description: SQL Agent - Service Account

- name: Create Service accounts
  win_domain_user:
    name: mdt
    password: '{{ ansible_password }}'
    state: present
    path: "OU=ServiceAccounts,OU=GO,{{ domain_path }}"
    groups:
    - Domain Admins

- name: Create Service accounts
  win_domain_user:
    name: loadgen_bot
    password: '{{ ansible_password }}'
    state: present
    path: "OU=ServiceAccounts,OU=GO,{{ domain_path }}"
    description: SQL Server - Service Account
    groups:
    - LoadGen

- name: Create LoadGen accounts
  win_domain_user:
    name: "LoadGen{{ item }}"
    password: '{{ ansible_password }}'
    state: present
    path: "OU=LoadGen,OU=GO,{{ domain_path }}"
    description: LoadGen simulation account
    groups:
    - LoadGen
  loop: "{{ range(250) | list }}"