---
- name: Ensure the required NuGet package provider is installed
  win_shell: Install-PackageProvider -Name "NuGet" -Force

- name: Install required PowerShell modules
  win_psmodule:
    name: "{{ item }}"
    state: present
    accept_license: true
    skip_publisher_check: true
  retries: 5
  delay: 30
  loop:
    - PowerShellGet
    - PackageManagement
    - DnsServerDsc

# - name: Stop the time service
#   win_service:
#     name: w32time
#     state: stopped

# - name: Set NTP Servers
#   win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ public_ntp }}"'

# - name: Start the time service
#   win_service:
#     name: w32time
#     state: started

- name: Install Active Directory
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: true
    include_management_tools: true
  register: result

- name: Create Domain
  win_domain:
    dns_domain_name: "{{ dns_domain_name }}"
    safe_mode_password: "{{ domain_password }}"
  register: ad

- name: Reboot
  win_reboot:
  when: ad.changed

- name: Create reverse DNS zone
  win_dsc:
    resource_name: DnsServerPrimaryZone
    Name: '{{ reverse_dns_zone[:-5] }}-.in-addr.arpa'
    Ensure: Present

- name: Create forward DNS zone
  win_shell: Add-DnsServerForwarder -IPAddress '{{ public_dns1 }}', '{{ public_dns2 }}' -PassThru

- block:
  - name: Install DHCP Services
    ansible.windows.win_feature:
      name: DHCP
      state: present
      include_sub_features: true
      include_management_tools: true

  - name: Create DHCP config
    win_shell: |
      $scope = Get-DhcpServerv4Scope
      if (!($scope.Name -eq '{{ dns_domain_name }}-Scope')) {
        Add-DhcpServerv4Scope -Name '{{ dns_domain_name }}-Scope' -StartRange {{ dhcp_start_range }} -EndRange {{ dhcp_end_range }} -SubnetMask {{ dhcp_subnetmask }} -State Active

        Set-DhcpServerv4OptionValue -OptionID 3 -Value {{ dhcp_router }} -ScopeID {{ dhcp_start_range }} -ComputerName {{ inventory_hostname }}.{{ dns_domain_name | lower }}
        Set-DhcpServerv4OptionValue -DnsDomain {{ dns_domain_name }} -DnsServer {{ ansible_host }} -Router {{ dhcp_router }}

        Add-DhcpServerInDC -DnsName {{ inventory_hostname }}.{{ dns_domain_name | lower }} -IPAddress {{ ansible_host }}
      }

    vars:
      ansible_become: true
      ansible_become_user: system
      ansible_become_method: runas

  when: lookup('env', 'platform') != 'azure'
