---
ansible: "{{ hostvars['localhost']['ansible'] }}"
loadgen: "{{ hostvars['localhost']['loadgen'] }}"
loadgen_bot: "{{ hostvars['localhost']['loadgen_bot'] }}"
sql_agt: "{{ hostvars['localhost']['sql_agt'] }}"
sql_svc: "{{ hostvars['localhost']['sql_svc'] }}"
vsphere_password: "{{ hostvars['localhost']['vsphere_password'] | default('') }}"
vsphere_username: "{{ hostvars['localhost']['vsphere_username'] | default('') }}"
vsphere_host: "{{ hostvars['localhost']['vsphere_host'] | default('') }}"
go_euc_platform: "{{ hostvars['localhost']['go_euc_platform'] | default('vmware') }}"
nutanix_password: "{{ hostvars['localhost']['nutanix_password'] | default('') }}"
nutanix_username: "{{ hostvars['localhost']['nutanix_username'] | default('') }}"
nutanix_host: "{{ hostvars['localhost']['nutanix_host'] | default('') }}"
nutanix_pc_password: "{{ hostvars['localhost']['nutanix_pc_password'] | default('') }}"
nutanix_pc_username: "{{ hostvars['localhost']['nutanix_pc_username'] | default('') }}"
nutanix_pc_host: "{{ hostvars['localhost']['nutanix_pc_host'] | default('') }}"
nutanix_cluster_name: "{{ hostvars['localhost']['nutanix_cluster_name'] | default('') }}"
nutanix_storage_name: "{{ hostvars['localhost']['nutanix_storage_name'] | default('') }}"
nutanix_network_name: "{{ hostvars['localhost']['nutanix_network_name'] | default('') }}"
influx_token: "{{ hostvars['localhost']['influx_token'] }}"
influx_url: "{{ hostvars['localhost']['influx_url'] }}"
influx_org: "{{ hostvars['localhost']['influx_org'] }}"