- name: Initialize managed disk
  community.windows.win_initialize_disk:
    disk_number: 1
    
- name: Full format the newly created partition as NTFS and label it
  community.windows.win_format:
    drive_letter: D
    file_system: NTFS
    new_label: Data
    full: True