---
- name: Create Citrix Storefront variables
  script: createsfvars.ps1
  args:
    creates: C:\Logs\sf-vars.xml
  environment:
    HostbaseUrl: "{{ HostbaseUrl }}"
    FarmServers: "{{ groups['ctx_sf'] | join(', ') }}"
    StoreVirtualPath: "{{ StoreVirtualPath }}"
    TransportType: "{{ TransportType }}"
    GatewayUrl: "{{ GatewayUrl }}"
    GatewaySTAUrls: "{{ GatewaySTAUrls }}"
    GatewayName: "{{ GatewayName }}"
  
- name: Copy the Citrix Storefront script file
  win_copy:
    src: createsfsite.ps1
    dest: C:\Windows\Temp\
    
- name: Collect Citrix Storefront folder stat
  win_stat:
    path: C:\inetpub\wwwroot\Citrix
  register: sf_info

- name: Start Citrix Storefront script
  win_shell: C:\Windows\Temp\createsfsite.ps1
  when: sf_info.stat.exists == False
  vars:
    ansible_become: yes
    ansible_become_user: system
    ansible_become_method: runas

# - name: Wait for passcode file
#   win_wait_for:
#     path: C:\Logs\passcode.txt
#     delay: 10
#   when: sf_info.stat.exists == False

# - name: Slurp passcode file
#   slurp:
#     src: C:\Logs\passcode.txt
#   register: passcode
# - name: Some debug
#   debug: msg="{{ passcode['content'] | b64decode | trim }}"