parameters:
- name: azureEnvironment
  displayName: Azure Environment
  type: string
  values:
  - Anton
  - Patrick
  - Ryan
  - Tom
- name: azureWorkspace
  displayName: Workspace
  type: string
  values:
  - Cards
  - Flowers
trigger:
- none

pr: none

variables:
- group: ${{ parameters.azureEnvironment }}

name: ${{ parameters.azureEnvironment }}_${{ parameters.azureWorkspace }}_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: packer
  displayName: Packer image deployment
  pool: ${{ parameters.azureEnvironment }}-${{ lower(parameters.azureWorkspace) }}
  workspace:
    clean: all

  steps:
  - script: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      apt-get update && apt-get install packer
    displayName: 'Download and install Packer'

  - task: PowerShell@2
    displayName: Packer variables
    inputs:
      targetType: 'inline'
      script: |
        $packerVariable = @()
        $packerVariable += "azure_client_id=`"$(azure_client_id)`""
        $packerVariable += "azure_client_secret=`"$(azure_client_secret)`""
        $packerVariable += "azure_subscription_id=`"$(azure_subscription_id)`""
        $packerVariable += "azure_tenant_id=`"$(azure_tenant_id)`""
        Set-Content -Value $packerVariable -Path azure.pkrvars.hcl -Force
      workingDirectory: '$(Build.Repository.LocalPath)/packer/azure'

  - task: CmdLine@2
    displayName: Packer init
    inputs:
      script: | 
        packer init image.pkr.hcl
      workingDirectory: '$(Build.Repository.LocalPath)/packer/azure'

  - task: CmdLine@2
    displayName: Deploy Packer build image
    inputs:
      script: | 
        packer build -var-file=azure.pkrvars.hcl .
      workingDirectory: '$(Build.Repository.LocalPath)/packer/azure'

