trigger:
- none

pr: none

pool: GO-EUC Linux


stages:
- stage: image_creation
  displayName: Image creation

  jobs:
  - template: vmware/image.yml
    parameters:
      name: 
      path: packer/vmware/windows/server/2022
      build: vsphere-iso.windows-server-standard-dexp
      variable_group: VMware

- stage: infra_dc
  displayName: Infra domain controller

  dependsOn: image_creation
  
  jobs:
  - template: vmware/infra.yml
    parameters:
      terraform_argument: -target=module.ActiveDirectory
      vmware_build: Create
      variable_group: VMware
      
- stage: infra_dc_config
  displayName: Infra domain controller config

  dependsOn: infra_dc
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: domain.yml
      variable_group: VMware


- stage: infra_deployment
  displayName: Infra deployment

  dependsOn: infra_dc_config
  
  jobs:
  - template: vmware/infra.yml
    parameters:
      vmware_build: Create
      variable_group: VMware

- stage: management_server_config
  displayName: Management server configuration

  dependsOn: sql_server_config
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: management.yml
      variable_group: VMware

- stage: sql_server_config
  displayName: SQL server configuration

  dependsOn: infra_deployment
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: mssql.yml
      variable_group: VMware

- stage: gateway_server_config
  displayName: RDGateway server configuration

  dependsOn: infra_deployment
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: rdgateway.yml
      variable_group: VMware

- stage: file_server_config
  displayName: File server configuration

  dependsOn: infra_deployment
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: file.yml
      variable_group: VMware

- stage: loadgen_bots
  displayName: LoadGen Bots configuration

  dependsOn: infra_deployment
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: loadgen.yml
      variable_group: VMware


- stage: citrix_license_server
  displayName: Citrix License Server configuration

  dependsOn: infra_deployment
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: citrix-license-server.yml
      variable_group: VMware

- stage: citrix_delivery_controller
  displayName: Citrix Delivery Controller configuration

  dependsOn: sql_server_config
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: citrix-delivery-controller.yml
      variable_group: VMware

- stage: citrix_storefront
  displayName: Citrix Storefront configuration

  dependsOn: citrix_delivery_controller
  
  jobs:
  - template: vmware/ansible.yml
    parameters:
      ansible_playbook: citrix-storefront.yml
      variable_group: VMware

# - template: /vmware/domain.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'

# - template: /vmware/ansible.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'