trigger:
- none

pr: none

pool: GO-EUC Linux


stages:
- stage: image_creation
  displayName: Image creation

  jobs:
  - template: vmware/image.yml
    parameters:
      variable_group: VMware

- stage: infra_dc
  displayName: Infra domain controller

  dependsOn: image_creation
  
  jobs:
  - template: vmware/infra-dc.yml
    parameters:
      vmware_build: Create
      variable_group: VMware
      azure_backend: $(azure_backend)

- stage: infra_dc_config
  displayName: Infra domain controller config

  dependsOn: infra_dc
  
  jobs:
  - template: vmware/domain.yml
    parameters:
      ansible_playbook: domain.yml
      variable_group: VMware
      azure_backend: $(azure_backend)


- stage: infra_deployment
  displayName: Infra deployment

  dependsOn: infra_dc_config
  
  jobs:
  - template: vmware/infra.yml
    parameters:
      vmware_build: Create
      variable_group: VMware
      azure_backend: $(azure_backend)

# - template: /vmware/domain.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'

# - template: /vmware/ansible.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'