trigger:
- none

pr: none

pool: GO-EUC Linux


stages:
- stage: image_creation
  displayName: Image creation

  jobs:
  - template: vmware/image.yml
    parameters:
      variable_group: VMware

- stage: infra_deployment
  displayName: Infra deployment

  dependsOn: image_creation
  
  jobs:
  - template: vmware/infra.yml
    parameters:
      vmware_build: Create
      variable_group: VMware

# - template: /vmware/domain.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'

# - template: /vmware/ansible.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'