trigger:
- none

pool: GO-EUC Linux

jobs:
- template: .devops/pipelines/vmware/image.yml
  parameters:
    variable_group: VMware

# - template: /vmware/domain.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'

# - template: /vmware/infra.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'

# - template: /vmware/ansible.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'