trigger:
- none

pr: none

pool: GO-EUC Linux

extends:
  template: vmware/image.yml
  parameters:
    variable_group: VMware

- template: vmware/infra.yml
  parameters:
    build: 'Create'
    variable_group: VMware

# - template: /vmware/domain.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'

# - template: /vmware/ansible.yml
#   parameters:
#     name: Linux
#     vmImage: 'ubuntu-latest'