FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update

RUN apt install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN add-apt-repository --yes --update ppa:ansible/ansible

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    git \
    iputils-ping \
    libcurl4 \
    libunwind8 \
    netcat \
    libssl1.0 \
    python3.8 \
    python3-pip \
    gnupg \
    wget \
    xorriso \
    mkisofs \
    whois \
    apt-transport-https \
  && rm -rf /var/lib/apt/lists/*

# Azure CLI
RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
  && rm -rf /var/lib/apt/lists/*

# Ansible and the azure requirements
RUN pip3 install ansible
RUN pip3 install "pywinrm>=0.3.0"

RUN ansible --version

RUN ansible-galaxy collection install azure.azcollection --force

RUN curl https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt --output requirements-azure.txt
RUN pip3 install -r requirements-azure.txt


# Microsoft PowerShell
RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb

RUN apt-get update
RUN apt install --fix-broken
RUN apt-get install -y powershell

# Hasicorp Packer
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt-get update && apt-get install packer

# Hasicorp Terraform
RUN apt-get update && apt-get install terraform

# Hashicorp Vault
RUN apt-get update && apt-get install vault

# Azure DevOps Agent
ARG TARGETARCH=linux-amd64

WORKDIR /azp

COPY ./start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]