---
# handlers file for roles/mssql
- name: reboot windows
  win_reboot:
    reboot_timeout: 3600
    post_reboot_delay: 60
  when: mssql_suppress_reboot == False

- name: restart sqlagent
  win_service:
    name: "SQLAgent${{ mssql_instance_name|upper }}"
    state: restarted