- name: Prints two lines of messages, but only if there is an environment value set
  ansible.builtin.debug:
    msg:
    - "Vault: {{ vault_name }}"
    - "Resource group: {{ resource_group }}"
    - "Ansible user: {{ ansible_user }}"

- name: Get Key Vault by name
  azure_rm_keyvault_info:
    resource_group: "{{ resource_group }}"
    name: "{{ vault_name }}"
  register: keyvault

- name: Set key vault URI fact
  set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

- name: Get secret value
  azure_rm_keyvaultsecret_info:
    vault_uri: "{{ keyvaulturi }}"
    name: "{{ ansible_user }}"
  register: kvSecret

- name: Password debug
  ansible.builtin.debug:
    msg:
    - "{{ kvSecret['secrets'][0]['secret'] }}"

- name: set secret fact my_password
  set_fact: 
    my_password: "{{ kvSecret['secrets'][0]['secret'] }}"
    cashable: true

- name: Password sql_admin
  ansible.builtin.debug:
    msg:
    - "{{ sql_admin }}"

- name: Get secret value
  azure_rm_keyvaultsecret_info:
    vault_uri: "{{ keyvaulturi }}"
    name: "{{ sql_admin }}"
  register: kvSecretSql

- name: Password debug
  ansible.builtin.debug:
    msg:
    - "{{ kvSecretSql['secrets'][0]['secret'] }}"

- name: set secret fact sql_password
  set_fact: 
    sql_password: "{{ kvSecretSql['secrets'][0]['secret'] }}"
    cashable: true

- name: Create group_vars directory
  file:
    path: group_vars
    state: directory

- name: Create group_vars file
  file:
    path: group_vars/dc.yml
    state: touch

- name: Output key ansible_password
  lineinfile:
    path: group_vars/dc.yml
    line: 'ansible_password: "{{ my_password }}"'
    
- name: Output key recovery_password
  lineinfile:
    path: group_vars/dc.yml
    line: 'recovery_password: "{{ my_password }}"'

- name: Create group_vars file
  file:
    path: group_vars/mgnt.yml
    state: touch

- name: Output key ansible_password
  lineinfile:
    path: group_vars/mgnt.yml
    line: 'ansible_password: "{{ my_password }}"'

- name: Output key sql_password
  lineinfile:
    path: group_vars/mgnt.yml
    line: 'sql_password: "{{ sql_password }}"'

- name: Create group_vars file
  file:
    path: group_vars/cc.yml
    state: touch

- name: Output key ansible_password
  lineinfile:
    path: group_vars/cc.yml
    line: 'ansible_password: "{{ my_password }}"'

- name: Store Citrix Organization ID variable
  lineinfile:
    path: group_vars/cc.yml
    line: "citrix_org_id: \"{{ lookup('env', 'citrix_org_id') }}\""

- name: Store Citrix Client ID variable
  lineinfile:
    path: group_vars/cc.yml
    line: "citrix_client_id: \"{{ lookup('env', 'citrix_client_id') }}\""

- name: Store Citrix Client Secret variable
  lineinfile:
    path: group_vars/cc.yml
    line: "citrix_client_secret: \"{{ lookup('env', 'citrix_client_secret') }}\""

- name: Store Citrix prefix variable
  lineinfile:
    path: group_vars/cc.yml
    line: "prefix: \"{{ lookup('env', 'prefix') }}\""

- name: Store Branch variable
  lineinfile:
    path: group_vars/cc.yml
    line: "branch: \"{{ lookup('env', 'branch') }}\""