---
- hosts: localhost
  connection: local
  gather_facts: yes
  collections:
    - azure.azcollection

  tasks:

  - name: Prints two lines of messages, but only if there is an environment value set
    ansible.builtin.debug:
      msg:
      - "Vault: {{ vault_name }}"
      - "Resource group: {{ resource_group }}"

  - name: Start the Azure Key Vault actions
    include_tasks: azure-keyvault.yml



# - name: Domain Controller
#   hosts: dc
#   roles:
#   - domain-controller
#   vars:
#     ansible_connection: winrm
#     ansible_winrm_transport: ntlm
#     ansible_winrm_server_cert_validation: ignore
#     ansible_port: 5985

- name: Management Server
  hosts: mgnt
  roles:
  - domain-join
  - loadgen
  vars:
    dns_domain_name: 'GO.EUC'
    domain_name: GO
    domain_admin_user: "GO\\{{ ansible_user }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985

# - name: Citrix Cloud Connector
#   hosts: cc
#   serial: 1
#   roles:
#   - domain-join
#   - citrix-cloud-connector
#   vars:
#     dns_domain_name: 'GO.EUC'
#     domain_admin_user: "GO\\{{ ansible_user }}"
#     ansible_connection: winrm
#     ansible_winrm_transport: ntlm
#     ansible_winrm_server_cert_validation: ignore
#     ansible_port: 5985