---
- name: Citrix Delivery Controller
  hosts: ctx_ddc
  roles:
  - domain-join
  - citrix-delivery-controller
  vars:
    citrix_iso_source: Citrix_Virtual_Apps_and_Desktops_7_2203_2000.iso
    dns_domain_name: 'GO.EUC'
    domain_name: GO
    domain_controller: "{{ groups['dc'][0] }}"
    domain_admin_user: "GO\\{{ ansible_user }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985