---
- name: Citrix License Server
  hosts: ctx_lic
  roles:
  - domain-join
  - citrix-license-server
  vars_files:
    - domain.yml
    - citrix.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
