---
- name: Domain join the Citrix Delivery Controller
  hosts: ctx_ddc
  roles:
    - domain-join
  vars_files:
    - ansible.yml
    - domain.yml
  vars:
    ansible_user: "{{ local_admin_user }}"

- name: Install and configure Citrix Delivery Controller
  hosts: ctx_ddc
  roles:
    - citrix-delivery-controller
  vars_files:
    - ansible.yml
    - citrix.yml
    - domain.yml
  vars:
    ansible_user: "{{ domain_admin_user }}"
