---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Install requirements
    include_tasks: vault.yml

- name: Domain join the Citrix License Server
  hosts: citrix_lic
  roles:
    - domain-join
  vars_files:
    - ansible.yml
    - local.yml
  vars:
    ou_path: "OU=Infra,OU=Machines,OU=GO"

- name: Install and configure Citrix License Server
  hosts: citrix_lic
  roles:
  - citrix-license-server
  vars_files:
    - citrix.yml
    - ansible.yml
    - domain.yml
