---
- name: Citrix Delivery Controller
  hosts: ctx_ddc
  roles:
  - domain-join
  - citrix-delivery-controller
  vars_files:
    - domain.yml
    - citrix.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985