---
# - hosts: localhost
#   connection: local
#   gather_facts: yes
#   collections:
#     - azure.azcollection

#   tasks:
#   - name: Start the Azure Key Vault actions
#     include_tasks: azure-keyvault.yml
#   when: lookup('env', 'azure') == 'true'

- name: Domain Controller
  hosts: dc
  roles:
    - domain-controller
  vars_files:
    - ansible.yml
    - domain.yml
