---
# - hosts: localhost
#   connection: local
#   gather_facts: yes
#   collections:
#     - azure.azcollection

#   tasks:
#   - name: Start the Azure Key Vault actions
#     include_tasks: azure-keyvault.yml
#   when: lookup('env', 'azure') == 'true'

- name: Domain Controller
  hosts: dc
  roles:
  - domain-controller
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
