---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Install requirements
    include_tasks: vault.yml

- name: Domain Controller
  hosts: dc
  roles:
    - domain-controller
  vars_files:
    - ansible.yml
    - domain.yml
    - accounts.yml
  vars:
    ansible_user: "{{ hostvars['localhost']['ansible_local_user'] }}"
    ansible_password: "{{ hostvars['localhost']['ansible_local_password'] }}"
