---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Install requirements
    include_tasks: vault.yml

- name: Domain join the VMware Horizon Connection Server
  hosts: vmware_hcs
  roles:
    - domain-join
  vars_files:
    - ansible.yml
    - local.yml
  vars:
    ou_path: "OU=Infra,OU=Machines,OU=GO"

- name: Install and configure VMware Horizon Connection Server
  hosts: vmware_hcs
  roles:
    - horizon-connection-server
  vars_files:
    - ansible.yml
    - accounts.yml
    - vmware.yml
    - domain.yml
