---
# - hosts: localhost
#   connection: local
#   gather_facts: yes
#   collections:
#     - azure.azcollection

#   tasks:
#   - name: Start the Azure Key Vault actions
#     include_tasks: azure-keyvault.yml

- name: LoadGen Bots
  hosts: lg_bots
  roles:
  - domain-join
  - citrix-receiver
  - loadgen-agent
  vars:
    dns_domain_name: 'GO.EUC'
    domain_name: GO
    domain_controller: "{{ groups['dc'][0] }}"
    domain_admin_user: "GO\\{{ ansible_user }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
