---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Install requirements and collect secrets
    include_tasks: vault.yml

- name: Domain join the Management Server
  hosts: mgmt
  roles:
    - domain-join
  vars_files:
    - ansible.yml
    - local.yml
  vars:
    ou_path: "OU=Infra,OU=Machines,OU=GO"

- name: Install and configure the Management Server
  hosts: mgmt
  roles:
    - loadgen
  vars_files:
    - ansible.yml
    - domain.yml
    - accounts.yml
    - loadgen.yml
  vars:
    telegraf_monitor_vsphere: true
    sql_admin: "GO\\sql_svc"
    sql_password: "{{ hostvars['localhost']['sql_svc'] }}"
    sql_server: "{{ groups['sql'][0] }}"
    sql_database: "LoadGen"
