---
# - hosts: localhost
#   connection: local
#   gather_facts: yes
#   collections:
#     - azure.azcollection

#   tasks:
#   - name: Start the Azure Key Vault actions
#     include_tasks: azure-keyvault.yml

- name: Management Server
  hosts: mgnt
  roles:
  - domain-join
  - management
  - mssql-studio
  - visual-studio-code
  - citrix-studio
  
  # - loadgen
  vars:
    dns_domain_name: 'GO.EUC'
    domain_name: GO
    domain_controller: "{{ groups['dc'][0] }}"
    domain_admin_user: "GO\\{{ ansible_user }}"
    sql_admin: "GO\\sql_svc"
    sql_password: "{{ ansible_password }}"
    sql_server: "{{ groups['sql'][0] }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985


