---
- name: Domain join the Management Server 
  hosts: mngt
  roles:
    - domain-join
  vars_files:
  - ansible.yml
  - domain.yml
  vars:
    ansible_user: "{{ local_admin_user }}"

- name: Install and configure the Management Server 
  hosts: mngt
  roles:
    - file-share
    - management
    - mssql-studio
    - visual-studio-code
    - loadgen
  vars_files:
    - ansible.yml
    - domain.yml
    - loadgen.yml
  vars:
    ansible_user: "{{ domain_admin_user }}"
    sql_admin: "GO\\sql_svc"
    sql_password: "{{ ansible_password }}"
    sql_server: "{{ groups['sql'][0] }}"
    sql_database: "LoadGen"
