---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Install requirements and collect secrets
    include_tasks: vault.yml

- name: Install Windows Updates and set timezone
  hosts: all
  tasks:

    - name: Set timezone to 'W. Europe Standard Time' (GMT+01:00)
      win_timezone:
        timezone: W. Europe Standard Time

    - name: Force reboot before
      win_reboot:

    - name: Install Windows Updates
      win_updates:
        category_names: '*'
        reboot: no
        state: installed
        log_path: C:\Windows\Temp\ansible_updates.txt

    - name: Force reboot after the Windows Updates
      win_reboot:
        reboot_timeout: 3600

  vars_files:
    - ansible.yml
    - domain.yml