---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Install requirements
    include_tasks: vault.yml

- name: Domain join
  hosts: "build[{{build_id}}]"
  roles:
    - domain-join
  vars_files:
    - ansible.yml
    - local.yml
  vars:
    ou_path: "OU=Builds,OU=Machines,OU=GO"

- name: Installation playbook for base image
  hosts: "build[{{build_id}}]"
  roles:
    - windows-image
  vars_files:
    - ansible.yml
    - domain.yml
    - citrix.yml
    - vmware.yml
    - loadgen.yml
    - nvidia.yml
