---
# ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╭╮╱╱╭╮╱╱╱╱╱╱╱╱╱╭╮╭╮╭╮╱╱╱╱╭╮╱╱╱╱╱╱╱╱╱╱╱╭━━━┳╮╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭╮
# ┃╭━╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃╭╮┃╱╱╱╱┃┃╱╱┃┃╱╱╱╱╱╱╱╱╱┃┃┃┃┃┃╱╱╱╱┃┃╱╱╱╱╱╱╱╱╱╱╱┃╭━╮┃┃╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃┃
# ┃╰━╯┣━━┳━━┫┃╭┳━━┳━╮┃╰╯╰┳╮╭┳┫┃╭━╯┣━━┳━╮╱╱╱╱┃┃┃┃┃┣━━┳━┫┃╭┳━━┳━╮╱╱╱╱┃╰━╯┃┃╭━━┳╮╱╭┫╰━┳━━┳━━┫┃╭╮
# ┃╭━━┫╭╮┃╭━┫╰╯┫┃━┫╭╯┃╭━╮┃┃┃┣┫┃┃╭╮┃┃━┫╭╯╭━━╮┃╰╯╰╯┃╭╮┃╭┫╰╯┫┃━┫╭╯╭━━╮┃╭━━┫┃┃╭╮┃┃╱┃┃╭╮┃╭╮┃╭╮┃╰╯╯
# ┃┃╱╱┃╭╮┃╰━┫╭╮┫┃━┫┃╱┃╰━╯┃╰╯┃┃╰┫╰╯┃┃━┫┃╱╰━━╯╰╮╭╮╭┫╰╯┃┃┃╭╮┫┃━┫┃╱╰━━╯┃┃╱╱┃╰┫╭╮┃╰━╯┃╰╯┃╰╯┃╰╯┃╭╮╮
# ╰╯╱╱╰╯╰┻━━┻╯╰┻━━┻╯╱╰━━━┻━━┻┻━┻━━┻━━┻╯╱╱╱╱╱╱╰╯╰╯╰━━┻╯╰╯╰┻━━┻╯╱╱╱╱╱╰╯╱╱╰━┻╯╰┻━╮╭┻━━┻━━┻━━┻╯╰╯
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯

- name: Packer Worker Playbook
  hosts: all
  roles:
  - role: citrix-vda
    when: ansible_facts['env'].delivery == 'citrix'
    
  - role: microsoft365apps

  - role: citrix-optimizer