---
- name: Installation playbook for base image
  hosts: builds
  roles:
<<<<<<< Updated upstream
  - role: citrix-vda
    when: lookup('env', 'delivery') == 'citrix'

  - role: microsoft365apps

  # - role: citrix-optimizer
=======
  - windows-image
  vars_files:
  - ansible.yml
  - domain.yml
  - citrix.yml
>>>>>>> Stashed changes
