---
# ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╭╮╱╱╭╮╱╱╱╱╱╱╱╱╱╭╮╭╮╭╮╱╱╱╱╭╮╱╱╱╱╱╱╱╱╱╱╱╭━━━┳╮╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭╮
# ┃╭━╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃╭╮┃╱╱╱╱┃┃╱╱┃┃╱╱╱╱╱╱╱╱╱┃┃┃┃┃┃╱╱╱╱┃┃╱╱╱╱╱╱╱╱╱╱╱┃╭━╮┃┃╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃┃
# ┃╰━╯┣━━┳━━┫┃╭┳━━┳━╮┃╰╯╰┳╮╭┳┫┃╭━╯┣━━┳━╮╱╱╱╱┃┃┃┃┃┣━━┳━┫┃╭┳━━┳━╮╱╱╱╱┃╰━╯┃┃╭━━┳╮╱╭┫╰━┳━━┳━━┫┃╭╮
# ┃╭━━┫╭╮┃╭━┫╰╯┫┃━┫╭╯┃╭━╮┃┃┃┣┫┃┃╭╮┃┃━┫╭╯╭━━╮┃╰╯╰╯┃╭╮┃╭┫╰╯┫┃━┫╭╯╭━━╮┃╭━━┫┃┃╭╮┃┃╱┃┃╭╮┃╭╮┃╭╮┃╰╯╯
# ┃┃╱╱┃╭╮┃╰━┫╭╮┫┃━┫┃╱┃╰━╯┃╰╯┃┃╰┫╰╯┃┃━┫┃╱╰━━╯╰╮╭╮╭┫╰╯┃┃┃╭╮┫┃━┫┃╱╰━━╯┃┃╱╱┃╰┫╭╮┃╰━╯┃╰╯┃╰╯┃╰╯┃╭╮╮
# ╰╯╱╱╰╯╰┻━━┻╯╰┻━━┻╯╱╰━━━┻━━┻┻━┻━━┻━━┻╯╱╱╱╱╱╱╰╯╰╯╰━━┻╯╰╯╰┻━━┻╯╱╱╱╱╱╰╯╱╱╰━┻╯╰┻━╮╭┻━━┻━━┻━━┻╯╰╯
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯

- name: Packer Worker Playbook
  hosts: all
  roles:
  - role: nvidia-driver
    when: lookup('env', 'vgpu') == 'true' 
    
  - role: citrix-vda
    when: lookup('env', 'delivery') == 'citrix' 
   
  - role: microsoft365apps

  - role: citrix-optimizer