---
# ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭━━╮╱╱╱╱╭╮╱╱╭╮╱╱╱╱╱╱╱╱╱╭╮╭╮╭╮╱╱╱╱╭╮╱╱╱╱╱╱╱╱╱╱╱╭━━━┳╮╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╭╮
# ┃╭━╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃╭╮┃╱╱╱╱┃┃╱╱┃┃╱╱╱╱╱╱╱╱╱┃┃┃┃┃┃╱╱╱╱┃┃╱╱╱╱╱╱╱╱╱╱╱┃╭━╮┃┃╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱┃┃
# ┃╰━╯┣━━┳━━┫┃╭┳━━┳━╮┃╰╯╰┳╮╭┳┫┃╭━╯┣━━┳━╮╱╱╱╱┃┃┃┃┃┣━━┳━┫┃╭┳━━┳━╮╱╱╱╱┃╰━╯┃┃╭━━┳╮╱╭┫╰━┳━━┳━━┫┃╭╮
# ┃╭━━┫╭╮┃╭━┫╰╯┫┃━┫╭╯┃╭━╮┃┃┃┣┫┃┃╭╮┃┃━┫╭╯╭━━╮┃╰╯╰╯┃╭╮┃╭┫╰╯┫┃━┫╭╯╭━━╮┃╭━━┫┃┃╭╮┃┃╱┃┃╭╮┃╭╮┃╭╮┃╰╯╯
# ┃┃╱╱┃╭╮┃╰━┫╭╮┫┃━┫┃╱┃╰━╯┃╰╯┃┃╰┫╰╯┃┃━┫┃╱╰━━╯╰╮╭╮╭┫╰╯┃┃┃╭╮┫┃━┫┃╱╰━━╯┃┃╱╱┃╰┫╭╮┃╰━╯┃╰╯┃╰╯┃╰╯┃╭╮╮
# ╰╯╱╱╰╯╰┻━━┻╯╰┻━━┻╯╱╰━━━┻━━┻┻━┻━━┻━━┻╯╱╱╱╱╱╱╰╯╰╯╰━━┻╯╰╯╰┻━━┻╯╱╱╱╱╱╰╯╱╱╰━┻╯╰┻━╮╭┻━━┻━━┻━━┻╯╰╯
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
# ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯

- name: Packer Worker Playbook
  hosts: all
  roles:
  - citrix-vda
  - microsoft365apps
  - citrix-optimizer
  - bis-f
