- name: Built the environment dictonary and variables
  set_fact:
    branch: "{{ lookup('env', 'branch') | lower }}"
    prefix: "{{ lookup('env', 'prefix') }}"
    branches:
        default: "pois" 
        cards:   "card"
        flowers: "flow"

- name: Set the environment short
  set_fact:
    environment_short: "{{branches[branch | lower]}}"

- name: Create directory structure
  win_file:
    path: C:\Download\Citrix
    state: directory

- name: Check if Cloud Connector is downloaded yet
  win_stat:
    path: C:\Download\Citrix\cwcconnector.exe
  register: download_file

- name: Download Citrix Cloud Connector
  win_get_url:
    url: "https://downloads.cloud.com/{{ citrix_org_id }}/connector/cwcconnector.exe"
    dest: C:\Download\Citrix\cwcconnector.exe
  when: download_file.stat.exists == False

- name: Collect API access token from Citrix Cloud
  win_uri:
    url: "https://api-eu.cloud.com/cctrustoauth2/{{ citrix_org_id }}/tokens/clients"
    method: POST
    content_type: application/x-www-form-urlencoded
    body: "grant_type=client_credentials&client_id={{ citrix_client_id }}&client_secret={{ citrix_client_secret }}"
    return_content: yes
  register: citrix_token
  
- name: Get Citrix resource locations
  win_uri:
    url: https://registry.citrixworkspacesapi.net/{{ citrix_org_id }}/resourcelocations
    method: GET
    content_type: application/json
    headers: "{'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    return_content: yes
  register: citrix_resource

- name: Collect the Citrix resource locations from output
  set_fact:
    citrix_resource_id: "{{ data | to_json | from_json | json_query(querystr) }}"
  vars:
    data: "{{ citrix_resource['json'] | lower }}"
    querystr: "items[?contains(name,'{{ prefix | lower }}-{{ environment_short }}-{{ deploymentname | lower }}-azure')].id | [0]"

- name: Create new resource location when location does not exists
  win_uri:
    url: https://registry.citrixworkspacesapi.net/{{ citrix_org_id }}/resourcelocations
    method: POST
    headers: "{'Authorization': 'CWSAuth bearer={{citrix_token.json.access_token}}'}"
    content_type: application/json
    body: "{'name': '{{ prefix | lower }}-{{ environment_short }}-{{ deploymentname | lower }}-azure', 'internalOnly': false, 'timeZone': 'GMT Standard Time', 'readOnly': false}"
    return_content: yes
  register: citrix_new_resource
  when: citrix_resource_id != None
  
- name: Define new resource location id
  set_fact:
    citrix_resource_id: "{{ citrix_new_resource['json'].id }}"
  when: citrix_resource_id != None

- name: Install Citrix Cloud Connector
  win_package:
    path: C:\Download\Citrix\cwcconnector.exe
    #product_id: '{E6CF2E41-E333-45D6-8EB6-CC429030F5A8}' # Citrix Cloud Services Agent System {096D19F4-D07A-4024-8003-E22B99118A15}
    creates_path : 'C:\Program Files\Citrix\CloudServices\Agent\Citrix.CloudServices.Agent.exe'
    arguments: /q /CustomerName:"{{ citrix_org_id }}" /ClientId:"{{ citrix_client_id }}" /ClientSecret:"{{ citrix_client_secret }}" /Location:"{{ citrix_resource_id }}" /AcceptTermsOfService:true
    expected_return_code: [0]
    state: present
  vars:
    ansible_become: yes
    ansible_become_user: system
    ansible_become_method: runas
